spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/beizke?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
    username: root
    password: root1234

